/*
 * Apollo Web Services
 *  # Rate limit:   The **Rate Limit** and **Rate Reset** are specified in the HTTP-header with `X-RateLimit-Limit` and `X-RateLimit-Reset`; the rate limit is *per* `IP`.
 *
 * The version of the OpenAPI document: 2.32.0
 * Contact: valentino.lauciani@ingv.it
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.ingv.apollo.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.ingv.apollo.model.Hyp2000arcSchemaEwLogo;
import org.ingv.apollo.model.Hyp2000arcSchemaEwMessage;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.ingv.apollo.JSON;

/**
 * Hyp2000arcSchema
 */
////////////@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-01-03T13:14:51.077355279Z[Etc/UTC]")
public class Hyp2000arcSchema {
  public static final String SERIALIZED_NAME_EW_MESSAGE = "ewMessage";
  @SerializedName(SERIALIZED_NAME_EW_MESSAGE)
  private Hyp2000arcSchemaEwMessage ewMessage;

  public static final String SERIALIZED_NAME_EW_LOGO = "ewLogo";
  @SerializedName(SERIALIZED_NAME_EW_LOGO)
  private Hyp2000arcSchemaEwLogo ewLogo;

  public Hyp2000arcSchema() {
  }

  public Hyp2000arcSchema ewMessage(Hyp2000arcSchemaEwMessage ewMessage) {
    this.ewMessage = ewMessage;
    return this;
  }

   /**
   * Get ewMessage
   * @return ewMessage
  **/
  @javax.annotation.Nullable
  public Hyp2000arcSchemaEwMessage getEwMessage() {
    return ewMessage;
  }

  public void setEwMessage(Hyp2000arcSchemaEwMessage ewMessage) {
    this.ewMessage = ewMessage;
  }


  public Hyp2000arcSchema ewLogo(Hyp2000arcSchemaEwLogo ewLogo) {
    this.ewLogo = ewLogo;
    return this;
  }

   /**
   * Get ewLogo
   * @return ewLogo
  **/
  @javax.annotation.Nullable
  public Hyp2000arcSchemaEwLogo getEwLogo() {
    return ewLogo;
  }

  public void setEwLogo(Hyp2000arcSchemaEwLogo ewLogo) {
    this.ewLogo = ewLogo;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Hyp2000arcSchema hyp2000arcSchema = (Hyp2000arcSchema) o;
    return Objects.equals(this.ewMessage, hyp2000arcSchema.ewMessage) &&
        Objects.equals(this.ewLogo, hyp2000arcSchema.ewLogo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(ewMessage, ewLogo);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Hyp2000arcSchema {\n");
    sb.append("    ewMessage: ").append(toIndentedString(ewMessage)).append("\n");
    sb.append("    ewLogo: ").append(toIndentedString(ewLogo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("ewMessage");
    openapiFields.add("ewLogo");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to Hyp2000arcSchema
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!Hyp2000arcSchema.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in Hyp2000arcSchema is not found in the empty JSON string", Hyp2000arcSchema.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!Hyp2000arcSchema.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `Hyp2000arcSchema` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `ewMessage`
      if (jsonObj.get("ewMessage") != null && !jsonObj.get("ewMessage").isJsonNull()) {
        Hyp2000arcSchemaEwMessage.validateJsonElement(jsonObj.get("ewMessage"));
      }
      // validate the optional field `ewLogo`
      if (jsonObj.get("ewLogo") != null && !jsonObj.get("ewLogo").isJsonNull()) {
        Hyp2000arcSchemaEwLogo.validateJsonElement(jsonObj.get("ewLogo"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!Hyp2000arcSchema.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'Hyp2000arcSchema' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<Hyp2000arcSchema> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(Hyp2000arcSchema.class));

       return (TypeAdapter<T>) new TypeAdapter<Hyp2000arcSchema>() {
           @Override
           public void write(JsonWriter out, Hyp2000arcSchema value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public Hyp2000arcSchema read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of Hyp2000arcSchema given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of Hyp2000arcSchema
  * @throws IOException if the JSON string is invalid with respect to Hyp2000arcSchema
  */
  public static Hyp2000arcSchema fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, Hyp2000arcSchema.class);
  }

 /**
  * Convert an instance of Hyp2000arcSchema to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

