/*
 * Apollo Web Services
 *  # Rate limit:   The **Rate Limit** and **Rate Reset** are specified in the HTTP-header with `X-RateLimit-Limit` and `X-RateLimit-Reset`; the rate limit is *per* `IP`.
 *
 * The version of the OpenAPI document: 2.32.0
 * Contact: valentino.lauciani@ingv.it
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.ingv.apollo.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.JsonElement;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Impulsive or emersio, pamp description | varchar(1)
 */
@JsonAdapter(PickEmersio.Adapter.class)
public enum PickEmersio {
  
  E("E"),
  
  I("I"),
  
  NULL("null");

  private String value;

  PickEmersio(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static PickEmersio fromValue(String value) {
    for (PickEmersio b : PickEmersio.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<PickEmersio> {
    @Override
    public void write(final JsonWriter jsonWriter, final PickEmersio enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public PickEmersio read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return PickEmersio.fromValue(value);
    }
  }

  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    String value = jsonElement.getAsString();
    PickEmersio.fromValue(value);
  }
}

