/*
 * Dante Web Services
 *       # Introduction   Dante is an API Web Service used for iteract with earthquake data stored in database (**quakedb**); the **quakedb** database schema is used at INGV.   Use other schema would require cration of specific `Model` and `Controller` but this is the potential of web services.      Dante provides a set of routes to store message **event**, **origin**, **magnitude**, **arrival**, **...**.      # Input   As input, Dante acept:   - A `json` message (view '**store**' spec below)    - An Eartworm `json` message (view '**earthworm api**' spec below) produced by **ew2openapi** module      # Output   As output, Dante has a RESTful api foreach database table and implement three specific routes:    - `events-group`: returns the preferred origin and the preferred magnitude from all clusterd events.    - `events`: returns the preferred origin and the preferred magnitude from the same instance.    - `event`: returns the full event (event, origins, magnitudes, arrivals, amplitude, etc...) from an **eventid** or **originid**_/_**originid**.        
 *
 * The version of the OpenAPI document: 3.22.2
 * Contact: valentino.lauciani@ingv.it
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.ingv.dante.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.ingv.dante.JSON;

/**
 * UpdateEventRequestDataEvent
 */
//@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-07-01T12:56:18.203916966Z[Etc/UTC]")
public class UpdateEventRequestDataEvent {
  public static final String SERIALIZED_NAME_TYPE_EVENT = "type_event";
  @SerializedName(SERIALIZED_NAME_TYPE_EVENT)
  private String typeEvent;

  public static final String SERIALIZED_NAME_EVENT_GROUP_ID = "event_group_id";
  @SerializedName(SERIALIZED_NAME_EVENT_GROUP_ID)
  private Long eventGroupId;

  public static final String SERIALIZED_NAME_PREFERRED_ORIGIN_ID = "preferred_origin_id";
  @SerializedName(SERIALIZED_NAME_PREFERRED_ORIGIN_ID)
  private Long preferredOriginId;

  public static final String SERIALIZED_NAME_PREFERRED_MAGNITUDE_ID = "preferred_magnitude_id";
  @SerializedName(SERIALIZED_NAME_PREFERRED_MAGNITUDE_ID)
  private Long preferredMagnitudeId;

  public static final String SERIALIZED_NAME_PREFERRED_FOCALMECHANISM_ID = "preferred_focalmechanism_id";
  @SerializedName(SERIALIZED_NAME_PREFERRED_FOCALMECHANISM_ID)
  private Long preferredFocalmechanismId;

  public UpdateEventRequestDataEvent() {
  }

  public UpdateEventRequestDataEvent typeEvent(String typeEvent) {
    this.typeEvent = typeEvent;
    return this;
  }

   /**
   * Name | varchar(255)
   * @return typeEvent
  **/
  @javax.annotation.Nullable
  public String getTypeEvent() {
    return typeEvent;
  }

  public void setTypeEvent(String typeEvent) {
    this.typeEvent = typeEvent;
  }


  public UpdateEventRequestDataEvent eventGroupId(Long eventGroupId) {
    this.eventGroupId = eventGroupId;
    return this;
  }

   /**
   * Link event group | bigint(20)
   * @return eventGroupId
  **/
  @javax.annotation.Nullable
  public Long getEventGroupId() {
    return eventGroupId;
  }

  public void setEventGroupId(Long eventGroupId) {
    this.eventGroupId = eventGroupId;
  }


  public UpdateEventRequestDataEvent preferredOriginId(Long preferredOriginId) {
    this.preferredOriginId = preferredOriginId;
    return this;
  }

   /**
   * Link: preferred origin. It can be NULL. | bigint(20)
   * @return preferredOriginId
  **/
  @javax.annotation.Nullable
  public Long getPreferredOriginId() {
    return preferredOriginId;
  }

  public void setPreferredOriginId(Long preferredOriginId) {
    this.preferredOriginId = preferredOriginId;
  }


  public UpdateEventRequestDataEvent preferredMagnitudeId(Long preferredMagnitudeId) {
    this.preferredMagnitudeId = preferredMagnitudeId;
    return this;
  }

   /**
   * Link: preferred magnitude. It can be NULL. | bigint(20)
   * @return preferredMagnitudeId
  **/
  @javax.annotation.Nullable
  public Long getPreferredMagnitudeId() {
    return preferredMagnitudeId;
  }

  public void setPreferredMagnitudeId(Long preferredMagnitudeId) {
    this.preferredMagnitudeId = preferredMagnitudeId;
  }


  public UpdateEventRequestDataEvent preferredFocalmechanismId(Long preferredFocalmechanismId) {
    this.preferredFocalmechanismId = preferredFocalmechanismId;
    return this;
  }

   /**
   * Link: preferred focalmechanism. It can be NULL. | bigint(20)
   * @return preferredFocalmechanismId
  **/
  @javax.annotation.Nullable
  public Long getPreferredFocalmechanismId() {
    return preferredFocalmechanismId;
  }

  public void setPreferredFocalmechanismId(Long preferredFocalmechanismId) {
    this.preferredFocalmechanismId = preferredFocalmechanismId;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the UpdateEventRequestDataEvent instance itself
   */
  public UpdateEventRequestDataEvent putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpdateEventRequestDataEvent updateEventRequestDataEvent = (UpdateEventRequestDataEvent) o;
    return Objects.equals(this.typeEvent, updateEventRequestDataEvent.typeEvent) &&
        Objects.equals(this.eventGroupId, updateEventRequestDataEvent.eventGroupId) &&
        Objects.equals(this.preferredOriginId, updateEventRequestDataEvent.preferredOriginId) &&
        Objects.equals(this.preferredMagnitudeId, updateEventRequestDataEvent.preferredMagnitudeId) &&
        Objects.equals(this.preferredFocalmechanismId, updateEventRequestDataEvent.preferredFocalmechanismId)&&
        Objects.equals(this.additionalProperties, updateEventRequestDataEvent.additionalProperties);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(typeEvent, eventGroupId, preferredOriginId, preferredMagnitudeId, preferredFocalmechanismId, additionalProperties);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdateEventRequestDataEvent {\n");
    sb.append("    typeEvent: ").append(toIndentedString(typeEvent)).append("\n");
    sb.append("    eventGroupId: ").append(toIndentedString(eventGroupId)).append("\n");
    sb.append("    preferredOriginId: ").append(toIndentedString(preferredOriginId)).append("\n");
    sb.append("    preferredMagnitudeId: ").append(toIndentedString(preferredMagnitudeId)).append("\n");
    sb.append("    preferredFocalmechanismId: ").append(toIndentedString(preferredFocalmechanismId)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("type_event");
    openapiFields.add("event_group_id");
    openapiFields.add("preferred_origin_id");
    openapiFields.add("preferred_magnitude_id");
    openapiFields.add("preferred_focalmechanism_id");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to UpdateEventRequestDataEvent
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!UpdateEventRequestDataEvent.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in UpdateEventRequestDataEvent is not found in the empty JSON string", UpdateEventRequestDataEvent.openapiRequiredFields.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("type_event") != null && !jsonObj.get("type_event").isJsonNull()) && !jsonObj.get("type_event").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `type_event` to be a primitive type in the JSON string but got `%s`", jsonObj.get("type_event").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!UpdateEventRequestDataEvent.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'UpdateEventRequestDataEvent' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<UpdateEventRequestDataEvent> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(UpdateEventRequestDataEvent.class));

       return (TypeAdapter<T>) new TypeAdapter<UpdateEventRequestDataEvent>() {
           @Override
           public void write(JsonWriter out, UpdateEventRequestDataEvent value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additional properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   JsonElement jsonElement = gson.toJsonTree(entry.getValue());
                   if (jsonElement.isJsonArray()) {
                     obj.add(entry.getKey(), jsonElement.getAsJsonArray());
                   } else {
                     obj.add(entry.getKey(), jsonElement.getAsJsonObject());
                   }
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public UpdateEventRequestDataEvent read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             JsonObject jsonObj = jsonElement.getAsJsonObject();
             // store additional fields in the deserialized instance
             UpdateEventRequestDataEvent instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of UpdateEventRequestDataEvent given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of UpdateEventRequestDataEvent
  * @throws IOException if the JSON string is invalid with respect to UpdateEventRequestDataEvent
  */
  public static UpdateEventRequestDataEvent fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, UpdateEventRequestDataEvent.class);
  }

 /**
  * Convert an instance of UpdateEventRequestDataEvent to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

